UsePermissions: true
UseCatchChance: true
LooseEggOnFail: true
UseVaultCost: false
UseItemCost: false
UseHealthPercentage: false
ExplosionEffect: true
SmokeEffect: false
NonPlayerCatching: false
PreventCatchingBabyAnimals: true
PreventCatchingTamedAnimals: true
PreventCatchingShearedSheeps: true
SpawnChickenOnSuccess: false
SpawnChickenOnFail: true
VaultTargetBankAccount: ""
DeleteVillagerInventoryOnCatch: false
CatchChance:
  Pig: 100.0
  Sheep: 100.0
  MushroomCow: 100.0
  Cow: 100.0
  Chicken: 100.0
  Squid: 100.0
  Wolf: 100.0
  Creeper: 0.0
  Skeleton: 100.0
  CaveSpider: 100.0
  Spider: 100.0
  PigZombie: 100.0
  Zombie: 100.0
  MagmaCube: 100.0
  Slime: 100.0
  Ghast: 0.0
  Enderman: 100.0
  Silverfish: 100.0
  Blaze: 0.0
  Villager: 100.0
  Ocelot: 100.0
  Witch: 100.0
  Bat: 100.0
  Horse: 100.0
  Endermite: 100.0
  Guardian: 100.0
  Rabbit: 100.0
  PolarBear: 100.0
  IronGolem: 100.0
VaultCost:
  Pig: 100.0
  Sheep: 100.0
  MushroomCow: 100.0
  Cow: 100.0
  Chicken: 100.0
  Squid: 100.0
  Wolf: 100.0
  Creeper: 100.0
  Skeleton: 100.0
  CaveSpider: 100.0
  Spider: 100.0
  PigZombie: 100.0
  Zombie: 100.0
  MagmaCube: 100.0
  Slime: 100.0
  Ghast: 100.0
  Enderman: 100.0
  Silverfish: 100.0
  Blaze: 100.0
  Villager: 100.0
  Ocelot: 100.0
  Witch: 100.0
  Bat: 100.0
  Horse: 100.0
  Endermite: 100.0
  Guardian: 100.0
  Rabbit: 100.0
  PolarBear: 100.0
  IronGolem: 100.0
ItemCost:
  ItemId: DIAMOND
  ItemData: 0
  Amount:
    Pig: 5
    Sheep: 5
    MushroomCow: 5
    Cow: 5
    Chicken: 5
    Squid: 5
    Wolf: 5
    Creeper: 5
    Skeleton: 5
    CaveSpider: 5
    Spider: 5
    PigZombie: 5
    Zombie: 5
    MagmaCube: 5
    Slime: 5
    Ghast: 5
    Enderman: 5
    Silverfish: 5
    Blaze: 5
    Villager: 5
    Ocelot: 5
    Witch: 5
    Bat: 5
    Horse: 5
    Endermite: 5
    Guardian: 5
    Rabbit: 5
    PolarBear: 5
    IronGolem: 5
HealthPercentage:
  Pig: 100.0
  Sheep: 100.0
  MushroomCow: 100.0
  Cow: 100.0
  Chicken: 100.0
  Squid: 100.0
  Wolf: 100.0
  Creeper: 100.0
  Skeleton: 100.0
  CaveSpider: 100.0
  Spider: 100.0
  PigZombie: 100.0
  Zombie: 100.0
  MagmaCube: 100.0
  Slime: 100.0
  Ghast: 100.0
  Enderman: 100.0
  Silverfish: 100.0
  Blaze: 100.0
  Villager: 100.0
  Ocelot: 100.0
  Witch: 100.0
  Bat: 100.0
  Horse: 100.0
  Endermite: 100.0
  Guardian: 100.0
  Rabbit: 100.0
  PolarBear: 100.0
  IronGolem: 100.0
Messages:
  PermissionFail: "You do not have permission to catch this mob!"
  VaultFail: "It costs %s dollars to catch this mob!"
  VaultSuccess: "You paid %s dollars for catching this mob!"
  ItemCostFail: "It costs %s gold nugget(s) to catch this mob!"
  ItemCostSuccess: "You paid %s gold nugget(s) for catching this mob!"
  CatchChanceFail: "You failed to catch this mob!"
  CatchChanceSuccess: ""
  HealthPercentageFail: "The mob has more than %s percent health left and cannot be caught!"
ConfigVersion: 2.7
